# fmt
[tasks.fmt]
dependencies = ["cargo-fmt", "deno-fmt", "python-fmt"]

[tasks.cargo-fmt]
command = "cargo"
args = ["fmt"]

[tasks.deno-fmt]
command = "deno"
args = ["fmt"]

[tasks.python-fmt]
command = "python3.12"
args = ["-m", "black", "."]

# fmt-check
[tasks.fmt-check]
dependencies = ["cargo-fmt-check", "deno-fmt-check", "python-fmt-check"]

[tasks.cargo-fmt-check]
command = "cargo"
args = ["fmt", "--check"]

[tasks.deno-fmt-check]
command = "deno"
args = ["fmt", "--check"]

[tasks.python-fmt-check]
command = "python3.12"
args = ["-m", "black", ".", "--check"]

# check
[tasks.check]
dependencies = ["cargo-check", "cargo-clippy", "deno-check", "python-check"]

[tasks.cargo-check]
command = "cargo"
args = ["check"]

[tasks.cargo-clippy]
command = "cargo"
args = ["clippy"]

[tasks.deno-check]
command = "deno"
args = ["check", "--allow-import", "static/main.js"]

[tasks.python-check]
command = "python3.12"
args = ["-m", "mypy", "."]

# test
[tasks.test]
dependencies = ["cargo-test", "python-test"]

[tasks.cargo-test]
command = "cargo"
args = ["test"]

[tasks.python-test]
command = "python3.12"
args = ["-m", "pytest", "-n", "2"]

# git hook setup
[tasks.install-git-hooks]
description = "Install pre-commit hook to run fmt-check and check"
script = [
    "mkdir -p .git/hooks",
    "echo '#!/bin/sh' > .git/hooks/pre-commit",
    "echo 'cargo make fmt-check || exit 1' >> .git/hooks/pre-commit",
    "echo 'cargo make check || exit 1' >> .git/hooks/pre-commit",
    "chmod +x .git/hooks/pre-commit"
]
