name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Install cargo-make
        run: cargo install cargo-make

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python packages
        run: pip install -r requirements.txt

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run format check
        run: cargo make fmt-check

      - name: Run cargo check
        run: cargo make check

      - name: Run cargo test
        run: cargo test

      - name: Run cargo clippy
        run: cargo clippy
